// Generate CORTEX_DEV_SESSION.md from DevSession

import type { DevSession } from '@cortex/protocol-twins';

export function generateMarkdown(session: DevSession): string {
  const timestamp = new Date(session.generatedAt).toISOString();
  const slug = session.description
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 40);

  const capsSections = session.capabilities
    .map(
      (cap) =>
        `### ${cap.agent} — ${cap.agent}.cortex.eth
**Role:** ${cap.role}
**Provides:** ${cap.provides.join(', ') || '(none)'}
**Needs from peers:** ${cap.needs.join(', ') || '(none)'}
**Verified:** ${cap.verified ? '✓' : '✗'}`,
    )
    .join('\n\n');

  const exchangesSections = session.peerExchanges
    .map(
      (ex) =>
        `### ${ex.from} → ${ex.to}
**Q:** ${ex.question}
**A** (verified=${ex.verified}, skill=${ex.skill}): ${ex.answer.slice(0, 300)}...`,
    )
    .join('\n\n');

  const orderList = session.implementationOrder
    .map((agent, i) => {
      const cap = session.capabilities.find((c) => c.agent === agent);
      const deps = session.dependencyGraph
        .filter((d) => d.to === agent)
        .map((d) => d.from)
        .join(', ');
      return `${i + 1}. **${agent}** — ${cap?.role || '?'} ${deps ? `(depends on: ${deps})` : '(no deps)'}`;
    })
    .join('\n');

  return `# Cortex Dev Session: ${slug}

**Project ID:** ${session.projectId}
**Generated:** ${timestamp}

## Project Brief

${session.description}

## Agent Capabilities (resolved via ENS)

${capsSections}

## AXL Peer Negotiations

${exchangesSections}

## Implementation Order

${orderList}

## Architecture Dependencies

\`\`\`
${session.dependencyGraph.map((d) => `${d.from} → ${d.to} (${d.dep})`).join('\n')}
\`\`\`

## Next Steps — Query Agents During Implementation

Agents remain available on their HTTP ports for live queries:

\`\`\`bash
# Ask zerog-builder (9013) to implement storage layer
curl http://localhost:9013/ask -X POST \\
  -H "Content-Type: application/json" \\
  -d '{"message":"Implement storage layer for: ${session.description}"}'

# Ask axl-builder (9023) to implement network layer
curl http://localhost:9023/ask -X POST \\
  -H "Content-Type: application/json" \\
  -d '{"message":"Implement network layer for: ${session.description}"}'

# Ask ens-builder (9033) to implement identity layer
curl http://localhost:9033/ask -X POST \\
  -H "Content-Type: application/json" \\
  -d '{"message":"Implement identity layer for: ${session.description}"}'
\`\`\`

---
Generated by Cortex DevBuddy — Multi-Agent Development Orchestration
`;
}
